const CAPABILITY_LABELS: Record<string, string> = {
  all: "全部能力",
  analysis: "数据分析",
  contract: "合同审查",
  acceptance_criteria: "验收口径",
  acceptance_testing: "验收测试",
  api_design: "接口设计",
  architecture_review: "架构评审",
  automation_testing: "自动化测试",
  backend_development: "后端研发",
  capacity_planning: "容量规划",
  change_management: "变更管理",
  code_review: "代码评审",
  contingency_plan: "应急预案",
  contract_design: "契约设计",
  crm: "客户管理",
  data: "数据处理",
  data_model_design: "数据模型",
  defect_analysis: "缺陷定位",
  dependency_check: "依赖检查",
  deployment_check: "上线检查",
  email: "邮件处理",
  frontend_development: "前端研发",
  general_processing: "通用处理",
  go_live_checklist: "上线清单",
  incident_review: "故障复盘",
  incident_triage: "事故分诊",
  integration_development: "联调集成",
  legal: "法务合规",
  log_diagnosis: "日志诊断",
  migration_planning: "迁移规划",
  monitoring_alerting: "监控告警",
  notification: "通知提醒",
  performance_tuning: "性能容量",
  postmortem: "复盘总结",
  prd_refinement: "PRD 完善",
  quality_gate: "质量门禁",
  quote: "报价处理",
  report: "报表分析",
  regression_testing: "回归测试",
  release_planning: "发布计划",
  requirement_analysis: "需求分析",
  risk: "风险识别",
  rollback_planning: "回滚预案",
  root_cause_analysis: "根因分析",
  sales: "销售协同",
  save_file: "保存文件",
  send_email: "发送邮件",
  service_orchestration: "服务编排",
  slo_tracking: "SLO 跟踪",
  scope_definition: "范围定义",
  solution_design: "技术方案",
  summarize: "内容总结",
  task_breakdown: "任务拆解",
  test_case_design: "测试用例",
  ui_integration: "界面联调",
  user_story: "用户故事",
  write_article: "文章撰写",
  write_report: "报告撰写",
}

export function capabilityLabel(capability: string): string {
  return CAPABILITY_LABELS[capability] || capability.replace(/_/g, " ")
}
